[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tinyworld = "AYPTCkaWoeEyQm4bzGqf4aLUm5JZYwFB8JGMLEwxyiBB"

[programs.devnet]
tinyworld = "AYPTCkaWoeEyQm4bzGqf4aLUm5JZYwFB8JGMLEwxyiBB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "C:/Users/tiger/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
